apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep1
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
      env: unit
  template:
    metadata:
      labels:
        tier: frontend
        env: unit
    spec:
      containers:
      - name: hello
        image: nginxdemos/hello
