apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep3
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
      env: fonc
  template:
    metadata:
      labels:
        tier: frontend
        env: fonc
    spec:
      containers:
      - name: hello
        image: nginxdemos/hello
